sudo: false
language: python
python:
#  - 3.5
  - 3.6
cache: apt
addons:
  apt:
    packages:
      - gfortran      

env:
  global:
    # List package dependencies for conda
    - CONDA_DEPS="cython numpy scipy h5py sphinx sphinx_rtd_theme ipython nbsphinx tqdm astropy configobj matplotlib numpydoc mpich mpi4py pytest-cov zarr gfortran_linux-64 gcc_linux-64" 
    # package name for test invocation
    - PACKAGENAME="hazel"

before_install:
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p $MINICONDA
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - conda activate testenv
  - conda install -c conda-forge $CONDA_DEPS  
  - conda deactivate
  - conda activate testenv
  - pip install coveralls
  
install:
  - python setup.py develop

script:
  - py.test -v --cov hazel

after_success:
  - coveralls
  # - cd docs

  # - bash ./deploy_docs.sh
