# https://autobencoder.com/2020-08-24-conda-actions/

name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10          
          conda-version: 'latest'
          activate-environment: test          
          auto-update-conda: true

      - shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda update -q conda
          conda info -a
          conda list
          conda install -c conda-forge Cython numpy scipy h5py sphinx sphinx_rtd_theme ipython nbsphinx tqdm astropy configobj matplotlib numpydoc mpich mpi4py pytest-cov zarr gfortran_linux-64 
          pip install coveralls

      - name: Build
        run: |
          python setup.py develop

      - name: Test with pytest
        run: |          
          py.test -v --cov hazel

      - name: Coveralls
        run: |
          coveralls
