# https://autobencoder.com/2020-08-24-conda-actions/

name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'          
          activate-environment: test          
          auto-activate-base: false
          channels: conda-forge          
          channel-priority: strict

      - name: Installation        
        run: |          
          conda info -a
          conda list
          conda install -c conda-forge Cython numpy scipy h5py sphinx sphinx_rtd_theme ipython nbsphinx tqdm astropy configobj matplotlib numpydoc mpich mpi4py pytest-cov zarr gfortran_linux-64 
          pip install coveralls

      - name: Build
        run: |
          conda list
          python setup.py develop

      - name: Test with pytest
        run: |          
          py.test -v --cov-report lcov --cov hazel

      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov

      # - name: Build wheels
        # uses: pypa/cibuildwheel@v2.16.0